{% set name = "pywaterml" %}

{% set version = "1.2.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7da2dee15fd5c4821e10f6a61f315b9bdc5754d6fb01b5faf87d548e3bc5538c

build:

  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - owslib
    - pandas
    - suds-community
    - tslearn
    - xmltodict
    - pyproj
    - cython
test:
  imports:
    - pywaterml
    - pywaterml.waterML
    - pywaterml.auxiliaryMod
    - pywaterml.analyzeData

  source_files:
    - tests/test_fast.py
  requires:
    - pytest
  commands:
    - pytest -vv tests/test_fast.py

about:
  home: https://github.com/romer8/pywaterml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The pywaterml is a package that lets you handle WaterML functions such as GetValues, GetSitesInfo, etc. In addition it lets offers extra functions such as mean interpolation for data with gaps
  doc_url: https://pywaterml.readthedocs.io/en/latest/index.html
  dev_url: https://hydroinformatics.byu.edu/

extra:
  recipe-maintainers:
    - romer8
