{% set name = "pywaterml" %}
{% set version = "1.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/romer8/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 435c0ff174c886b973fc353cb092421b4e1fb7dcadc0610e0650fdd88fd3d2b9

build:

  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - owslib
    - pandas
    - python
    - suds-jurko
    - scikit-learn ==0.22
    - tslearn
    - xmltodict
    - cython
test:
  imports:
    - pywaterml
    - pywaterml.waterML
    - pywaterml.auxiliaryMod
    - pywaterml.analyzeData

about:
  home: https://github.com/romer8/pywaterml
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The pywaterml is a package that lets you handle WaterML functions such as GetValues, GetSitesInfo, etc. In addition it lets offers extra functions such as mean interpolation for data with gaps
  doc_url: https://pywaterml.readthedocs.io/en/latest/index.html
  dev_url: https://hydroinformatics.byu.edu/

extra:
  recipe-maintainers:
    - romer8
